- name: Dump autoload
  command: composer dump-autoload
  args:
    chdir: "{{ backend_dir }}"

- name: Migrate database
  command: php artisan migrate
  args:
    chdir: "{{ backend_dir }}"
  become: true
  become_method: sudo

- name: Seed database
  command: php artisan db:seed
  args:
    chdir: "{{ backend_dir }}"

