- name: Check variables
  debug: 
    var: frontend_dir

- name: Generate nginx site config
  template:
    src: nginx-frontend.j2
    dest: /etc/nginx/sites-available/frontend
  notify: Reload Nginx

- name: Enable frontend site
  file:
    src: /etc/nginx/sites-available/frontend
    dest: /etc/nginx/sites-enabled/frontend
    state: link
  notify: Reload Nginx

- name: Check nginx
  command: nginx -t
  register: resultcheck

- name: Show check results
  debug:
    var: resultcheck.stdout_lines

- name: Start frontend
  shell: bash -c "source ~/.nvm/nvm.sh && yarn start &"
  args:
    chdir: "{{ frontend_dir }}"
  register: resultstart

- name: Show start results
  debug:
    var: resultstart.stdout_lines
  
- name: Test frontend with curl
  uri:
    url: http://localhost:3000
    method: GET
    return_content: yes
  register: result

- name: Show results
  debug:
    var: result.content
   