- name: Check variables
  debug: 
    var: backend_dir

- name: Generate nginx backend site
  template:
    src: nginx-backend.j2
    dest: /etc/nginx/sites-available/backend
  notify: Reload Nginx

- name: Enable backend site
  file:
    src: /etc/nginx/sites-available/backend
    dest: /etc/nginx/sites-enabled/backend
    state: link
  notify: Reload Nginx

- name: Check nginx configuration
  command: nginx -t
  register: resultnginx

- name: Show nginx result
  debug:
    msg: "{{ resultnginx }}"
  when: resultnginx.stdout.find('successful') == -1

- name: Start backend
  command: "php artisan serve"
  args:
    chdir: "{{ backend_dir }}"