- hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - env/vars.yml
  roles: 
    - name: frontend-build
      vars:
        frontend_src: "https://github.com/elshiraphine/fe-todo"
        frontend_dir: "/var/www/frontend"
      - name: backend-build
        vars:
          backend_src: "https://github.com/elshiraphine/be-todo"
          backend_dir: "/var/www/backend"
          mysql_database: "laravel"
          mysql_user: "root"
          mysql_password: "root"