- import_playbook: prepare.yml
- import_playbook: build.yml
- import_playbook: migrate.yml
- import_playbook: deploy.yml

- hosts: localhost
  vars_files:
    - env/vars.yml
  gather_facts: true
  become: true