- hosts: all
  gather_facts: true
  become: true
  vars_files:
    - env/vars.yml
  roles: 
    - name: mysql-prepare
      vars:
        mysql_root_password: "{{ mysql_root_password }}"
    - name: nginx-prepare