- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates=/home/{{ user }}/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 0.10 && nvm alias default 0.10"
    creates=/home/{{ user }}/.nvm/alias

- name: Yarn GPG
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Importing Yarn Package
  copy:
    content: "deb https://dl.yarnpkg.com/debian/ stable main"
    dest: /etc/apt/sources.list.d/yarn.list

- name: Installing Nodejs + Yarn
  apt:
    name:
      - yarn
    update_cache: true

- name: Clone from repo
  git:
    repo: "{{ frontend_src }}"
    dest: "{{ frontend_dir }}"
    clone: yes
    update: yes

- name: Check node and yarn version
  command: node -v && yarn -v
  register: resultdependencies

- name: Show dependencies
  debug:
    var: resultdependencies.stdout_lines

- name: Change ownership
  file:
    path: "{{ frontend_dir }}"
    owner: "www-data"
    group: "www-data"
    recurse: yes
 
- name: Install yarn packages
  command: yarn install
  args:
    chdir: "{{ frontend_dir }}"
  
- name: Build frontend
  command: yarn build
  args:
    chdir: "{{ frontend_dir }}"